// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loader: typeof import('./src/components/loader.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavCard: typeof import('./src/components/nav-card.vue')['default']
    NavHeader: typeof import('./src/components/nav-header.vue')['default']
    Paganation: typeof import('./src/components/Paganation.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
    ValidateForm: typeof import('./src/components/ValidateForm.vue')['default']
    ValidateInput: typeof import('./src/components/ValidateInput.vue')['default']
    'ValidateInput copy': typeof import('./src/components/ValidateInput copy.vue')['default']
    ValidateInput2: typeof import('./src/components/ValidateInput2.vue')['default']
  }
}

export {}
